name: PriDE CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17]
        database: [hsql, sqlite]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven with database ${{ matrix.database }}
        run: mvn clean test -B -P travis -Duser.name=${{ matrix.database }} --settings config/mvnsettings-for-github-actions.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
